# Generated by Django 2.2.16 on 2022-06-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220618_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genres',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='titles', through='reviews.GenreTitle', to='reviews.Genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.Titles'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterUniqueTogether(
            name='genretitle',
            unique_together=set(),
        ),
    ]
