# Generated by Django 2.2.16 on 2022-06-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220622_0052'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='titles',
            constraint=models.UniqueConstraint(fields=('id', 'category'), name='title_category'),
        ),
    ]
