# Generated by Django 2.2.16 on 2022-06-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220622_0154'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='titles',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='title_category'),
        ),
    ]
