# Generated by Django 2.2.16 on 2022-06-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220622_0856'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='titles',
            name='title_category',
        ),
    ]
