# Generated by Django 2.2.16 on 2022-06-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220622_1454'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genretitle',
            name='title_genre',
        ),
    ]
